<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>controller_node</name>
  <version>0.0.1</version>
  <description>Nodo Controlador: adaptador de entrada/salida ROS2 alrededor de un KinematicsPort (PoE, GA, DH, o un doble de pruebas)</description>
  <maintainer email="chris@example.com">chris</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>shared_kernel</depend>
  <depend>ros2_kit</depend>
  <depend>urdf_kit</depend>
  <depend>python3-numpy</depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
